---
deployment:
  tasks:
    - export: /home/np1gv5e4fvfz/public_html/    # Destination directory where your React project will be deployed
      branch: main    # Branch to deploy (change this to your main branch name)
      script: |
        export DEPLOYPATH=/home/np1gv5e4fvfz/public_html/
        npm install --legacy-peer-deps
        npm run build
        /bin/cp -R dist $DEPLOYPATH
